os: osx
osx_image: xcode10.1
sudo: required
env:
  global:
  - PACKAGE="/tmp/VineServer.zip"
addons:
  # artifacts:
  #   s3_region: us-west-1
  #   paths:
  #   - "$PACKAGE"
  homebrew:
    packages:
    - libjpeg-turbo
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $PACKAGE
  skip_cleanup: true
  on:
    tags: true
    
install:
- sudo ln -s "/usr/local/opt/libjpeg-turbo" "/opt/libjpeg-turbo"

script:
- xcodebuild -configuration Deployment -scheme "Vine Server Package" build
